name: Deploy FE and BE

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2' # Specify the version of Node.js you are using
          cache: npm

      # Install dependencies for BE (Strapi)
      - name: Install BE dependencies
        run: |
          cd tano  # assuming the backend folder is named "backend"
          npm install

      - name: Build BE
        run: |
          npm run build

      # Install dependencies for FE (React)
      - name: Install FE dependencies
        run: |
          cd ../tano-fe  # assuming the frontend folder is named "frontend"
          npm install

      # Build React (Frontend)
      - name: Build FE
        run: |
          npm run build

      # Deploy Backend and Frontend to Server using ssh-deploy
      - name: Deploy to Server (Frontend and Backend)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          SOURCE: './'
          TARGET: '/root/Tano_Porfolio'

      # Restart Backend (Strapi) and Frontend (React) using PM2
      - name: Restart BE and FE with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # Your server IP or domain
          username: ${{ secrets.SERVER_USER }} # Your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # The SSH private key secret
          script: |
            # Restart Backend (Strapi) using PM2
            cd /root/Tano_Porfolio/tano
            npm install
            pm2 restart server || pm2 start npm --name "server" -- start || exit

            # Restart Frontend (React) using PM2
            cd /root/Tano_Porfolio/tano-fe
            npm install
            pm2 restart fe || pm2 start npm --name "fe" -- start || exit
